#!/bin/bash

dir="$1"

# No directory has been provided, use current
if [ -z "$dir" ]
then
    dir="`pwd`"
fi

# Make sure directory ends with "/"
if [[ $dir != */ ]]
then
	dir="$dir/*"
else
	dir="$dir*"
fi

# Loop all sub-directories
for f in $dir
do
	# Only interested in git directories
	[ -d "$f/.git" ] || continue

  # Check if directory is a git repository (useless now)
	if [ -d "$f/.git" ]
	then
    echo "${f}"
		cd ../
	else
		echo "Not a git repository"
	fi
	echo
done

