#!/bin/sh

dir="$1"

# No directory has been provided, use current
if [ -z "$dir" ]
then
    dir="`pwd`"
fi

# Make sure directory ends with "/"
if [[ $dir != */ ]]
then
	dir="$dir/*"
else
	dir="$dir*"
fi

# Loop all sub-directories
for f in $dir
do
	# Only interested in git directories
	[ -d "$f/.git" ] || continue

  # Check if directory is a git repository (useless now)
	if [ -d "$f/.git" ]
	then
		cd $f
		mod1=$(git status | grep modified -c)
		mod2=$(git status | grep Untracked -c)
		mod3=$(git status | grep 'Your branch is ahead' -c)
    mod4=$(git status | grep 'Changes not staged' -c)
    
    mod=$(($mod1 + $mod2 + $mod3 + $mod4))

		# Check if everything is peachy keen
		if [ $mod -eq 0 ]
		then
      continue
    else
      echo "${f}"
      if [ $mod1 -ne 0 ]
      then
      echo -en "\033[0;35m"
      echo "[$(git status | grep modified -c)] Modified files"
      echo -en "\033[0m"
      fi

      if [ $mod2 -ne 0 ]
      then
      echo -en "\033[0;35m"
      echo "[Some] Untracked files"
      echo -en "\033[0m"
      fi

      if [ $mod3 -ne 0 ]
      then
        echo -en "\033[0;31m"
        echo "Unpushed commit"
        echo -en "\033[0m"
      fi

      if [ $mod4 -ne 0 ]
      then
        echo -en "\033[0;31m"
        echo "[Some] deleted files"
        echo -en "\033[0m"
      fi
		fi

		cd ../
	else
		echo "Not a git repository"
	fi

	echo
done

